CREATE TABLE USUARIO (
  CPF VARCHAR(11) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  cartao VARCHAR(16),
  cep VARCHAR(8),
  detalhamento VARCHAR(255),
  ultimo_acesso DATETIME
);

CREATE TABLE TELEFONE (
  CPF VARCHAR(11) NOT NULL,
  telefone VARCHAR(11) NOT NULL,
  PRIMARY KEY (CPF, telefone),
  FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);

CREATE TABLE CONTA (
  CPF VARCHAR(11) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  PRIMARY KEY (CPF),
  FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);