CREATE TABLE FEEDBACK (
  ID INT PRIMARY KEY,
  CPF VARCHAR(11) NOT NULL,
  email VARCHAR(255) NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  FOREIGN KEY (CPF, email) REFERENCES USUARIO(CPF, email),
  FOREIGN KEY (titulo) REFERENCES VIDEO(titulo)
);