CREATE TABLE CONTA (
  senha VARCHAR(255)
);
CREATE TABLE USUÁRIO (
  CPF CHAR(11) PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  cartão CHAR(16),
  cep CHAR(8),
  detalhamento VARCHAR(255),
  senha VARCHAR(255),
  último_acesso TIMESTAMP,
  FOREIGN KEY (senha) REFERENCES CONTA(senha)
);
CREATE TABLE TELEFONE (
  CPF CHAR(11),
  telefone VARCHAR(20),
  PRIMARY KEY (CPF, telefone),
  FOREIGN KEY (CPF) REFERENCES USUÁRIO(CPF)
);