CREATE TABLE INTERPRETA (
  CPF_Ator VARCHAR(11) NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  ID_Personagem INT,
  PRIMARY KEY (CPF_Ator, titulo),
  FOREIGN KEY (CPF_Ator) REFERENCES ATOR(CPF),
  FOREIGN KEY (titulo) REFERENCES VIDEO(titulo),
  FOREIGN KEY (ID_Personagem) REFERENCES PERSONAGEM(ID_Personagem)
);