CREATE TABLE CONTA (
  senha VARCHAR(255) PRIMARY KEY
);
CREATE TABLE USUARIO (
  CPF CHAR(11) PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  cartao CHAR(16),
  cep CHAR(8),
  detalhamento VARCHAR(255),
  senha VARCHAR(255),
  último_acesso TIMESTAMP,
  FOREIGN KEY (senha) REFERENCES CONTA(senha)
);
CREATE TABLE TELEFONE (
  CPF CHAR(11),
  telefone VARCHAR(20),
  PRIMARY KEY (CPF, telefone),
  FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);
CREATE TABLE MENSALIDADE (
  CPF CHAR(11) NOT NULL,
  mes_ano DATE NOT NULL,
  valor_pago DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (CPF, mes_ano),
  FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);
CREATE TABLE ATOR (
  CPF char(11) PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  CPF_Prot CHAR(11),
  FOREIGN KEY (CPF_Prot) REFERENCES ATOR(CPF)
);
CREATE TABLE PERSONAGEM (
  ID_Personagem INT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL
);
CREATE TABLE VIDEO (
  titulo VARCHAR(255) PRIMARY KEY,
  ano INT NOT NULL,
  duracao INT NOT NULL
);
CREATE TABLE FILME (
  titulo VARCHAR(255) PRIMARY KEY,
  genero VARCHAR(255) NOT NULL,
  FOREIGN KEY (titulo) REFERENCES VIDEO(titulo)
);
CREATE TABLE SERIE (
  titulo VARCHAR(255) NOT NULL,
  temporada INT NOT NULL,
  episodio INT NOT NULL,
  PRIMARY KEY (titulo, temporada, episodio),
  FOREIGN KEY (titulo) REFERENCES VIDEO(titulo)
);
CREATE TABLE VISUALIZA (
  CPF CHAR(11),
  titulo VARCHAR(255),
  PRIMARY KEY (CPF, titulo),
  FOREIGN KEY (CPF) REFERENCES USUARIO(CPF),
  FOREIGN KEY (titulo) REFERENCES VIDEO(titulo)
);
CREATE TABLE FEEDBACK_USUARIO (
  ID_feedback INT PRIMARY KEY,
  CPF CHAR(11),
  titulo VARCHAR(255),
  FOREIGN KEY (CPF,titulo) REFERENCES VISUALIZA(CPF,titulo)
);
CREATE TABLE INTERPRETA (
  CPF_Ator CHAR(11) NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  ID_Personagem INT,
  PRIMARY KEY (CPF_Ator, titulo),
  FOREIGN KEY (CPF_Ator) REFERENCES ATOR(CPF),
  FOREIGN KEY (titulo) REFERENCES VIDEO(titulo),
  FOREIGN KEY (ID_Personagem) REFERENCES PERSONAGEM(ID_Personagem)
);